# Generated by Django 2.2.4 on 2019-08-13 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='order_placed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Placed', blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='task_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='celery_task_id'),
        ),
    ]
